# PeMS_Orange_County 数据集
dataset:
  data_dir: data/PeMS_Orange_County
  step_num_in: 12
  step_num_out: 12
  num_nodes: 211
  input_size: 3
  batch_size: 64
  device: cuda:0

DCP_STGNet:
  num_block: 2
  kernel_size: 5
  num_cheb_filter: 128
  num_time_filter: 128
  conv_type: cheb
  K: 3
  init_feature_num: 64
  adj_mx_path: data/PeMS_Orange_County/graph/A.npy,data/PeMS_Orange_County/graph/distanceA.npy,data/PeMS_Orange_County/graph/priceA.npy


ASTGCN:

   adj_mx_path: data/PeMS_Orange_County/graph/A.npy,data/PeMS_Orange_County/graph/distanceA.npy,data/PeMS_Orange_County/graph/priceA.npy

